# Generated by Django 2.2.7 on 2019-11-30 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
